name: DVC CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  run-pipeline:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Set up DVC and authenticate with DagsHub
        run: |
          pip install dvc
          dvc remote modify origin auth basic
          dvc remote modify origin user "${{ secrets.DAGSHUB_USER }}"
          dvc remote modify origin password "${{ secrets.DAGSHUB_TOKEN }}"
          dvc pull

      - name: Reproduce pipeline
        run: |
          dvc repro

      - name: Commit updated files (model.pkl, dvc.lock)
        run: |
          git config --global user.email "aliawan05500@gmail.com"
          git config --global user.name "Ali"
          git add dvc.lock models/model.pkl
          git commit -m "Auto update: retrained model and lock file" || echo "No changes to commit"
          git push origin main
